/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Export: typeof import('./src/components/dialog/Export.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LeftLayout: typeof import('./src/components/LeftLayout.vue')['default']
    LightLayout: typeof import('./src/components/LightLayout.vue')['default']
    MainLayout: typeof import('./src/components/MainLayout.vue')['default']
    MainLayoutMask: typeof import('./src/components/MainLayoutMask.vue')['default']
    MapImage: typeof import('./src/components/model-info-material-layout/MapImage.vue')['default']
    ModelInfoAnimationLayout: typeof import('./src/components/ModelInfoAnimationLayout.vue')['default']
    ModelInfoBasicLayout: typeof import('./src/components/ModelInfoBasicLayout.vue')['default']
    ModelInfoLayout: typeof import('./src/components/ModelInfoLayout.vue')['default']
    ModelInfoMaterialLayout: typeof import('./src/components/ModelInfoMaterialLayout.vue')['default']
    ModelInfoNodeLayout: typeof import('./src/components/ModelInfoNodeLayout.vue')['default']
    OpenFromLocal: typeof import('./src/components/dialog/OpenFromLocal.vue')['default']
    OpenFromURL: typeof import('./src/components/dialog/OpenFromURL.vue')['default']
    RightLayout: typeof import('./src/components/RightLayout.vue')['default']
    SettingLayout: typeof import('./src/components/SettingLayout.vue')['default']
    SubTitleLabel: typeof import('./src/components/model-info-material-layout/SubTitleLabel.vue')['default']
    TextureItem: typeof import('./src/components/model-info-material-layout/TextureItem.vue')['default']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
    View3D: typeof import('./src/components/View3D.vue')['default']
  }
}
