/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LeftContainer: typeof import('./src/components/LeftContainer.vue')['default']
    LeftLayout: typeof import('./src/components/LeftLayout.vue')['default']
    MainLayout: typeof import('./src/components/MainLayout.vue')['default']
    ModelAnimationLayout: typeof import('./src/components/ModelAnimationLayout.vue')['default']
    ModelInfoAnimationLayout: typeof import('./src/components/ModelInfoAnimationLayout.vue')['default']
    ModelInfoBasicLayout: typeof import('./src/components/ModelInfoBasicLayout.vue')['default']
    ModelInfoLayout: typeof import('./src/components/ModelInfoLayout.vue')['default']
    ModelInfoNodeLayout: typeof import('./src/components/ModelInfoNodeLayout.vue')['default']
    ModelNodeLayout: typeof import('./src/components/ModelNodeLayout.vue')['default']
    OpenFromLocal: typeof import('./src/components/dialog/OpenFromLocal.vue')['default']
    OpenFromURL: typeof import('./src/components/dialog/OpenFromURL.vue')['default']
    RightLayout: typeof import('./src/components/RightLayout.vue')['default']
    SettingLayout: typeof import('./src/components/SettingLayout.vue')['default']
    SvgButton: typeof import('./src/components/SvgButton.vue')['default']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
    View: typeof import('./src/components/View.vue')['default']
    View3D: typeof import('./src/components/View3D.vue')['default']
  }
}
